### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by zyk-miao** [hcanyz/flutter-netease-music-api#1]
{
I/flutter ( 7657):          code: -462,
I/flutter ( 7657):          data: {
I/flutter ( 7657):              actionCode: "1102401",
I/flutter ( 7657):              verifyType: 50,
I/flutter ( 7657):              verifyId: 1,
I/flutter ( 7657):              verifyUrl: "",
I/flutter ( 7657):              blockText: "网络太拥挤，请稍候再试。",
I/flutter ( 7657):              verifyToken: null,
I/flutter ( 7657):              btnText: null,
I/flutter ( 7657):              orpheusUrl: null,
I/flutter ( 7657):              frontRuleIds: [1102401]
I/flutter ( 7657):              params: {event_id: 00299884049522196495, sign: c7b3aeacee5c10e439678fdb93e5c88e},
I/flutter ( 7657):              url: null
I/flutter ( 7657):         }
I/flutter ( 7657):          message: "网络太拥挤，请稍候再试。"
I/flutter ( 7657):     }

**Comment by 2697a** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/24308269/206996910-e9a7f61d-ef78-49c2-81dc-26550af1dba3.png">
cookies里面的os换成android就可以了
